name: github-ci

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout source
      - name: Checkout
        uses: actions/checkout@v4
      # generate artifacts
      - name: install and build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm test
          pnpm coverage
          pnpm build
      - name: github-ci
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
